sources:
  - name: dcl-marketplace
    handler:
      graphql:
        # endpoint: https://api.thegraph.com/subgraphs/name/decentraland/marketplace
        endpoint: https://gateway.thegraph.com/api/${STUDIO_API_KEY}/subgraphs/id/GnwyhKp8uQkktC3vgMxWpg9f9qea75WQ6GXTxjW6BbZq
          
documents:
  - dcl.graphql